# Site settings
title: CV
email: jaeyounglee978@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curriculum Vitae page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaeyounglee978.github.io" # the base hostname & protocol for your site
twitter_username: aru_soc
github_username:  jaeyounglee978

# Build settings
markdown: kramdown
permalink: pretty